# Generated by Django 5.2.14 on 2026-05-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('location', models.CharField(blank=True, default='', max_length=180, verbose_name='Konum')),
                ('institution', models.CharField(blank=True, default='', max_length=180, verbose_name='Bağlı Kurum')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-posta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'İletişim Bilgisi',
                'verbose_name_plural': 'İletişim Bilgileri',
                'ordering': ('-is_active', 'email'),
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('title', models.CharField(max_length=180, verbose_name='Okul/Bölüm')),
                ('period', models.CharField(blank=True, default='', max_length=80, verbose_name='Tarih')),
                ('subtitle', models.CharField(blank=True, default='', max_length=180, verbose_name='Alt Başlık')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Eğitim',
                'verbose_name_plural': 'Eğitimler',
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('title', models.CharField(max_length=180, verbose_name='Görev')),
                ('period', models.CharField(blank=True, default='', max_length=80, verbose_name='Tarih')),
                ('company', models.CharField(blank=True, default='', max_length=180, verbose_name='Kurum')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'İş Deneyimi',
                'verbose_name_plural': 'İş Deneyimleri',
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('title', models.CharField(max_length=180, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('image', models.CharField(blank=True, default='', max_length=255, verbose_name='Görsel')),
                ('alt_text', models.CharField(blank=True, default='', max_length=180, verbose_name='Görsel Açıklaması')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Çalışma',
                'verbose_name_plural': 'Çalışmalar',
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('full_name', models.CharField(default='', max_length=120, verbose_name='Ad Soyad')),
                ('profile_title', models.CharField(blank=True, default='', max_length=180, verbose_name='Profil Başlığı')),
                ('hero_titles', models.CharField(blank=True, default='', max_length=500, verbose_name='Hero Yazıları')),
                ('hero_description', models.CharField(blank=True, default='', max_length=500, verbose_name='Hero Açıklaması')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Özet')),
                ('about_intro', models.TextField(blank=True, default='', verbose_name='Hakkımda 1. Paragraf')),
                ('about_middle', models.TextField(blank=True, default='', verbose_name='Hakkımda 2. Paragraf')),
                ('about_footer', models.TextField(blank=True, default='', verbose_name='Hakkımda 3. Paragraf')),
                ('education_label', models.CharField(blank=True, default='', max_length=180, verbose_name='Eğitim Bilgisi')),
                ('location', models.CharField(blank=True, default='', max_length=180, verbose_name='Konum')),
                ('hero_image', models.CharField(blank=True, default='img/alperen-main.jpeg', max_length=255, verbose_name='Hero Görseli')),
                ('profile_image', models.CharField(blank=True, default='img/alperen-profile.jpg', max_length=255, verbose_name='Profil Görseli')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profil',
                'ordering': ('-is_active', 'full_name'),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('icon', models.CharField(default='bi bi-check-circle', max_length=80, verbose_name='Bootstrap Icon')),
                ('title', models.CharField(max_length=180, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Yetkinlik Kartı',
                'verbose_name_plural': 'Yetkinlik Kartları',
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('name', models.CharField(max_length=120, verbose_name='Beceri')),
                ('percent', models.PositiveSmallIntegerField(default=80, verbose_name='Yüzde')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Beceri',
                'verbose_name_plural': 'Beceriler',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('label', models.CharField(max_length=80, verbose_name='Etiket')),
                ('icon', models.CharField(default='bi bi-link', max_length=80, verbose_name='Bootstrap Icon')),
                ('url', models.CharField(max_length=255, verbose_name='Bağlantı')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Sosyal Bağlantı',
                'verbose_name_plural': 'Sosyal Bağlantılar',
                'ordering': ('order', 'label'),
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='Değer')),
                ('label', models.CharField(max_length=120, verbose_name='Etiket')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Sayaç',
                'verbose_name_plural': 'Sayaçlar',
                'ordering': ('order', 'label'),
            },
        ),
    ]
